/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.test.runners.codegen;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/fir/fir2ir/testData/codegen/box")
@TestDataPath("$PROJECT_ROOT")
public class FirSpecificBlackBoxCodegenTestGenerated extends AbstractFirBlackBoxCodegenTest {
    @Test
    public void testAllFilesPresentInBox() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/fir2ir/testData/codegen/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("sample.kt")
    public void testSample() throws Exception {
        runTest("compiler/fir/fir2ir/testData/codegen/box/sample.kt");
    }

    @Nested
    @TestMetadata("compiler/fir/fir2ir/testData/codegen/box/unionTypes")
    @TestDataPath("$PROJECT_ROOT")
    public class UnionTypes {
        @Test
        public void testAllFilesPresentInUnionTypes() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/fir2ir/testData/codegen/box/unionTypes"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("applicability.kt")
        public void testApplicability() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/applicability.kt");
        }

        @Test
        @TestMetadata("callFromCatch.kt")
        public void testCallFromCatch() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/callFromCatch.kt");
        }

        @Test
        @TestMetadata("callResolution.kt")
        public void testCallResolution() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/callResolution.kt");
        }

        @Test
        @TestMetadata("inapplicableJavaCall.kt")
        public void testInapplicableJavaCall() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/inapplicableJavaCall.kt");
        }

        @Test
        @TestMetadata("interfacesApplicability.kt")
        public void testInterfacesApplicability() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/interfacesApplicability.kt");
        }

        @Test
        @TestMetadata("localVariable.kt")
        public void testLocalVariable() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/localVariable.kt");
        }

        @Test
        @TestMetadata("mayBe.kt")
        public void testMayBe() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/mayBe.kt");
        }

        @Test
        @TestMetadata("propertyInConstructor.kt")
        public void testPropertyInConstructor() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/propertyInConstructor.kt");
        }

        @Test
        @TestMetadata("refiedTypeParameters.kt")
        public void testRefiedTypeParameters() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/refiedTypeParameters.kt");
        }

        @Test
        @TestMetadata("simpleMulticatch.kt")
        public void testSimpleMulticatch() throws Exception {
            runTest("compiler/fir/fir2ir/testData/codegen/box/unionTypes/simpleMulticatch.kt");
        }
    }
}
